#!/usr/bin/env python
# Not a .py to prevent ST from thinking this is a plugin

import inspect
import os.path

from pip.vcs.git import Git


INSTALL_DIR = os.path.join(os.path.dirname(inspect.getfile(inspect.currentframe())), 'package_control/deps/')


DEPENDENCIES = [
    ('oscrypto', 'https://github.com/wbond/oscrypto.git', '0.16.0'),
    ('asn1crypto', 'https://github.com/wbond/asn1crypto.git', '0.18.0')
]


def main():
    for dep, url, rev in DEPENDENCIES:
        print('Installing {} ({}) from {}'.format(dep, rev, url))

        Git(
            'git+{}@{}'.format(url, rev)
        ).obtain(
            os.path.join(INSTALL_DIR, dep)
        )

    init_file = os.path.join(INSTALL_DIR, '__init__.py')

    if not os.path.exists(init_file):
        print('Creating __init__.py')
        open(init_file, 'w').close()


if __name__ == '__main__':
        main()
